import Head from "next/head";

// components
import { FoodIndex } from "../modules/food/index";
import { JobIndex } from "../modules/job/index";
import { PayIndex } from "../modules/pay/index";
import { RecipesIndex } from "../modules/recipes/index";
import { Nav } from "../components/Nav";
import { LoginIndex } from "../modules/login/index";
import { RegisterIndex } from "../modules/register/index";

// style
import { MainSection, Section, BlankSpace } from "../styles/index";
import { useState } from "react";

export default function Home() {
  const [showLogin, setShowLogin] = useState(false);
  const [showRegister, setShowRegister] = useState(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainSection>
        <Section>
          <Nav />
          <PayIndex />
          <FoodIndex />
          <RecipesIndex />
          <JobIndex />
          <BlankSpace />
          {showRegister && <RegisterIndex />}
          {showLogin && <LoginIndex />}
        </Section>
      </MainSection>
    </>
  );
}
